# Generated by Django 5.1.5 on 2025-01-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=200, null=True),
        ),
    ]
