# Generated by Django 5.1.5 on 2025-02-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_review_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_image',
            field=models.ImageField(blank=True, default='df.jpg', null=True, upload_to=''),
        ),
    ]
