# Generated by Django 5.1.5 on 2025-03-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_review_owner_alter_review_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total']},
        ),
    ]
